### ISSUE TITLE
Create column model and and column_issue join table 

### ISSUE THREAD

**Issue by awaxman11** [CarlosPlusPlus/ghanban#20]
Column  | columns_issues
------------- | -------------
id  | column_id
board_id  | issue_id
label_name |

**Comment by CarlosPlusPlus** [comment]
If the relationship between these two models is:

A **column** `belongs_to` a **board** and a **board** `has_many` columns, then we don't need a join table. Having the board_id in the **column** model should suffice.

**Comment by CarlosPlusPlus** [comment]
Ah, never mind regarding my previous comment.

There are 2 separate tables that are being created for different purposes:

1. Association between **board** and **column**.
2. Association between columns and issues.

Let's go over the second association a bit more in-depth --- if an issue can belong to multiple columns, what happens when it 'changes' state from column to column? Do we post information back to GitHub at that point?
